### ISSUE TITLE
It tries to load content page when going to taxon url like "/t/categories", etc.

### ISSUE THREAD

**Issue by oleksify** [citrus/spree_essentials#1]
Completely breakes taxon routes

spree 0.60
ruby ree 1.87
osx

**Comment by citrus** [comment]
I'm on Spree 0.60.0, ruby 1.9.2p180 and OSX and can't recreate this.. Can you please provide me with the error message so I don't have to setup a 1.8.7 environment? 

Thanks!

Also, this issue is probably related to [spree_essential_cms](https://github.com/citrus/spree_essential_cms) not spree_essentials, right?

**Comment by oleksify** [comment]
This is what console prints:

Started GET "/t/katalogh/gitaristam" for 127.0.0.1 at Sun May 29 22:38:23 +0300 2011
  SQL (0.8ms)  SHOW TABLES
  SQL (0.8ms)  SHOW TABLES
  SQL (0.6ms)  SHOW TABLES
  SQL (0.7ms)  SHOW TABLES
  SQL (0.6ms)  SHOW TABLES
  SQL (0.7ms)  SHOW TABLES
  SQL (0.5ms)  describe `roles_users`
  SQL (0.5ms)  describe `product_groups_products`
  SQL (2.1ms)  describe `products_taxons`
  SQL (0.5ms)  describe `option_values_variants`
  SQL (0.8ms)  SHOW TABLES
  SQL (1.0ms)  SHOW TABLES
  SQL (0.9ms)  describe `product_groups_products`
  SQL (0.7ms)  SHOW TABLES
  SQL (0.6ms)  describe `products_promotion_rules`
  SQL (0.4ms)  describe `products_promotion_rules`
  SQL (0.4ms)  describe `promotion_rules_users`
  SQL (0.8ms)  SHOW TABLES
  SQL (0.7ms)  SHOW TABLES
  SQL (0.7ms)  SHOW TABLES
  SQL (0.7ms)  SHOW TABLES
  SQL (0.6ms)  SHOW TABLES
[Barista] Compiling all scripts for barista
[Barista] Compiling all coffeescripts
  Processing by TaxonsController#show as HTML
  Parameters: {"id"=>"katalogh/gitaristam"}
  User Load (0.1ms)  SELECT `users`.\* FROM `users` WHERE `users`.`id` = 1057526560 LIMIT 1
  Page Load (0.1ms)  SELECT `pages`.\* FROM `pages` WHERE `pages`.`path` = '/t/katalogh/gitaristam' LIMIT 1
  Page Load (0.1ms)  SELECT `pages`.\* FROM `pages` WHERE `pages`.`accessible` = 1 AND `pages`.`visible` = 1 ORDER BY position
  SQL (0.5ms)  describe `products_taxons`
  SQL (1.1ms)  describe `properties_prototypes`
  SQL (0.7ms)  SHOW TABLES
  Property Load (0.0ms)  SELECT `properties`.\* FROM `properties` WHERE `properties`.`name` = 'brand' LIMIT 1
  SQL (0.6ms)  SHOW TABLES
  Taxon Load (0.2ms)  SELECT `taxons`.\* FROM `taxons` WHERE `taxons`.`permalink` = 'katalogh/gitaristam' LIMIT 1
Completed   in 243ms
Rendered public/404.html (0.3ms)

**Comment by citrus** [comment]
It looks like the last thing spree is looking for before rendering the 404 page is a taxon with the permalink 'katalogh/gitaristam'. Does that taxon exist?

**Comment by oleksify** [comment]
Yes

## 

Alexey "DevilCoders" Topolyanskiy

**Comment by citrus** [comment]
what version/branch are you using? this error would be related to [spree_essential_cms](https://github.com/citrus/spree_essential_cms) anyways, right?

**Comment by oleksify** [comment]
Yes, i guess I should post it there. I;m using git master

**Comment by citrus** [comment]
you don't have to repost.. have you run a `bundle update spree_essential_cms` yet?

**Comment by citrus** [comment]
I'm just confused why the `/t/katalogh/gitaristam` url is passing through the router the way it is.. it shouldn't even look for a page with that url.. from the router:

``` ruby
class PossiblePage
  def self.matches?(request)
    path = request.fullpath
    return false if path =~ /(^\/(admin|account|cart|checkout|content|login|pg\/|orders|products|s\/|signup|states|t\/|tax_categories|session|shipments|user))/
    count = Page.active.where(:path => path).count
    0 < count    
  end
end
```

**Comment by oleksify** [comment]
Yes, I check that and was very confused. Will try to update and we'll see

**Comment by oleksify** [comment]
Sorry, it was spree issue with taxons, partially resolve it using some user's patch.

**Comment by citrus** [comment]
no worries glad we figured it out!
