### ISSUE TITLE
Compatibility with spree_core 1.3.0

### ISSUE THREAD

**Issue by sacha75** [citrus/spree_essentials#12]
Hi, since the new Spree update in 1.2 stable the spree essentials is not compatible anymore. Could you check if everything is working right and if yes update the dependency to match also spree_core 1.3 ?

Thank you !

**Comment by citrus** [comment]
Sorry I don't have time to keep this extension up to date.

**Comment by sacha75** [comment]
Hi citrus,

Thank you for your answer and thank for leaving it open source in the first place.
