### ISSUE TITLE
image browser not showing any images

### ISSUE THREAD

**Issue by rounders** [citrus/spree_essentials#2]
I'm just trying out spree_essentials along with spree_essentials_cms on a spree 0.70.3 project and it looks very good. One issue that I'm having difficulties with is the images.  I've uploaded a few images but when I select the Image Browser, no images actually show up.

**Comment by rounders** [comment]
it turned out to be user error :-) I incorrectly assumed that I needed to upload images through the images section instead of the 'Uploads' menu item.

**Comment by citrus** [comment]
Right on, cheers!
