### ISSUE TITLE
attachment_file_size migration fails with duplicate row in spree 1.1

### ISSUE THREAD

**Issue by jsimmons** [citrus/spree_essentials#7]
https://github.com/citrus/spree_essentials/blob/master/db/migrate/20120306185618_add_attachment_file_size_to_assets.rb
conflicts with
https://github.com/spree/spree/commit/832e69278d8fe861a9971c2631ebd7e2356dac6e

**Comment by citrus** [comment]
Builds were breaking since we didn't remove the the `copy_migrations` method from the install generator.. this is fixed in 429af81
